cluster.name: "docker-cluster"
network.host: 0.0.0.0

indices.queries.cache.size: 2%
#indices.queries.cache.enabled: true

slm.history_index_enabled: false
xpack.watcher.enabled: false

indices.memory.index_buffer_size: 512MB
node.roles: [ master, ingest, data_hot, data ]
xpack.security.enabled: true
